spring:
  datasource:
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false
    username: root
    password: Vitylin97
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
       ddl-auto: update

hibernate:
  dialect: org.hibernate.dialect.MySQL8Dialect

User-agent: Mozilla/5.0 (Windows; U; WindowsNT 5.1; en-US; rv1.8.1.6) Gecko/20070725 Firefox/2.0.0.6

